Repository milvus-io/milvus-insight, pull requests merged in 2021-07, with the labels that each got.

#120 update milvus-node-sdk
  server/package.json
  server/src/collections/collections.service.ts
  server/src/milvus/milvus.service.ts
  server/yarn.lock
Labels: size/S

#123 Update README.md
  README.md
Labels: size/S

#122 add insert ui
  client/package.json
  client/src/assets/imgs/insert/fail.png
  client/src/assets/imgs/insert/success.png
  client/src/components/customButton/CustomButton.tsx
  client/src/components/customDialog/CustomDialogTitle.tsx
  client/src/components/customDialog/DialogTemplate.tsx
  client/src/components/customDialog/Types.ts
  client/src/components/customSelector/CustomSelector.tsx
  client/src/components/customSelector/Types.ts
  client/src/components/grid/Grid.tsx
  client/src/components/grid/Table.tsx
  client/src/components/grid/TableEditableHead.tsx
  client/src/components/grid/Types.ts
  client/src/components/icons/Icons.tsx
  client/src/components/icons/Types.ts
  client/src/components/insert/Container.tsx
  client/src/components/insert/Import.tsx
  client/src/components/insert/Preview.tsx
  client/src/components/insert/Status.tsx
  client/src/components/insert/Types.ts
  client/src/components/menu/SimpleMenu.tsx
  client/src/components/menu/Types.ts
  client/src/components/uploader/Types.ts
  client/src/components/uploader/Uploader.tsx
  client/src/consts/Insert.ts
  client/src/i18n/cn/insert.ts
  client/src/i18n/en/insert.ts
  client/src/pages/collections/Collections.tsx
  client/src/pages/collections/CreateFields.tsx
  client/src/pages/partitions/Partitions.tsx
  client/src/pages/schema/CreateForm.tsx
  client/src/pages/schema/Schema.tsx
  client/src/styles/theme.ts
  client/src/utils/Insert.ts
  client/yarn.lock
Labels: size/XL

#124 add insert api
  server/package.json
  server/src/collections/collections.controller.ts
  server/src/collections/collections.service.ts
  server/src/collections/dto.ts
  server/src/milvus/dto.ts
  server/src/milvus/milvus.controller.ts
  server/src/milvus/milvus.service.ts
  server/src/utils/ConsoleLogger.ts
  server/yarn.lock
Labels: size/M

#125 add search api
  server/src/collections/collections.controller.ts
  server/src/collections/collections.service.ts
  server/src/collections/dto.ts
Labels: size/M

#126 update insert interactions
  client/src/components/grid/ToolBar.tsx
  client/src/components/grid/Types.ts
  client/src/components/insert/Container.tsx
  client/src/components/insert/Import.tsx
  client/src/components/insert/Preview.tsx
  client/src/components/insert/Status.tsx
  client/src/components/insert/Types.ts
  client/src/components/menu/SimpleMenu.tsx
  client/src/components/uploader/Types.ts
  client/src/components/uploader/Uploader.tsx
  client/src/http/Collection.ts
  client/src/http/Milvus.ts
  client/src/pages/collections/Collections.tsx
  client/src/pages/collections/Types.ts
  client/src/pages/partitions/Partitions.tsx
  client/src/pages/schema/Types.ts
  client/src/utils/Insert.ts
Labels: size/XL

#127 fix fetch partition, update http size limit and timeout
  client/src/components/insert/Container.tsx
  client/src/components/uploader/Uploader.tsx
  client/src/http/Axios.ts
  server/package.json
  server/src/main.ts
  server/yarn.lock
Labels: size/S

#134 Fix: Login: Should trim input of the address
  client/src/pages/connect/Connect.tsx
  client/src/utils/Format.ts
Labels: size/S

#138 fix index params and add document title
  .gitignore
  client/src/components/insert/Import.tsx
  client/src/context/Auth.tsx
  client/src/http/Index.ts
  client/src/pages/schema/Create.tsx
  client/src/pages/schema/Schema.tsx
  client/src/utils/Common.ts
  client/src/utils/Format.ts
  server/generate-csv.ts
  server/package.json
  server/src/main.ts
  server/yarn.lock
Labels: size/L

#136 add cache example
  server/package.json
  server/src/cache/config.ts
  server/src/collections/collections.controller.ts
  server/src/collections/collections.module.ts
  server/yarn.lock
Labels: size/M

#145 Fix #141: On schema page, the checkboxes shouldn't be there
  client/src/pages/schema/Schema.tsx
Labels: size/XS

#149 add cache layer
  client/package.json
  client/src/pages/connect/Connect.tsx
  client/yarn.lock
  server/package.json
  server/src/events/events.gateway.ts
  server/src/events/events.module.ts
  server/yarn.lock
Labels: size/XXL

#147 No tooltip on disabled item #131
  client/src/components/grid/ToolBar.tsx
  client/src/components/grid/Types.ts
  client/src/i18n/cn/collection.ts
  client/src/i18n/en/collection.ts
  client/src/pages/collections/Collections.tsx
Labels: size/S

#153 fix: Can not create index in BinaryVector.
  client/src/consts/Milvus.tsx
  client/src/hooks/Form.ts
  client/src/pages/schema/Create.tsx
  client/src/pages/schema/Types.ts
  client/src/utils/Form.ts
Labels: size/L

#152 feat: Add Advanced Search
  client/src/assets/icons/copy.svg
  client/src/components/advancedSearch/Condition.tsx
  client/src/components/advancedSearch/ConditionGroup.tsx
  client/src/components/advancedSearch/CopyButton.tsx
  client/src/components/advancedSearch/Dialog.tsx
  client/src/components/advancedSearch/Filter.tsx
  client/src/components/advancedSearch/Types.ts
  client/src/components/advancedSearch/index.tsx
  client/src/components/customDialog/DialogTemplate.tsx
  client/src/components/customDialog/Types.ts
  client/src/components/icons/Icons.tsx
  client/src/components/icons/Types.ts
  client/src/utils/Common.ts
Labels: size/XXL

#151 add vector seach
  client/src/assets/icons/nav-search.svg
  client/src/assets/icons/search.svg
  client/src/components/advancedSearch/Filter.tsx
  client/src/components/advancedSearch/Types.ts
  client/src/components/icons/Icons.tsx
  client/src/components/icons/Types.ts
  client/src/components/insert/Preview.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/menu/SimpleMenu.tsx
  client/src/components/menu/Types.ts
  client/src/consts/Milvus.tsx
  client/src/hooks/Navigation.ts
  client/src/http/BaseModel.ts
  client/src/http/Collection.ts
  client/src/http/Index.ts
  client/src/i18n/cn/nav.ts
  client/src/i18n/cn/search.ts
  client/src/i18n/cn/warning.ts
  client/src/i18n/en/nav.ts
  client/src/i18n/en/search.ts
  client/src/i18n/en/warning.ts
  client/src/i18n/index.ts
  client/src/pages/connect/Connect.tsx
  client/src/pages/schema/Create.tsx
  client/src/pages/schema/Schema.tsx
  client/src/pages/schema/Types.ts
  client/src/pages/seach/Constants.ts
  client/src/pages/seach/SearchParams.tsx
  client/src/pages/seach/Styles.ts
  client/src/pages/seach/Types.ts
  client/src/pages/seach/VectorSearch.tsx
  client/src/router/Config.ts
  client/src/router/Types.ts
  client/src/utils/Format.ts
  client/src/utils/Insert.ts
  client/src/utils/Validation.ts
  client/src/utils/search.ts
Labels: size/XXL

#156 Fix autoid and add createdtime
  client/src/components/insert/Container.tsx
  client/src/components/insert/Import.tsx
  client/src/components/insert/Preview.tsx
  client/src/components/insert/Types.ts
  client/src/pages/collections/Create.tsx
  client/src/pages/connect/Connect.tsx
  server/package.json
  server/src/collections/collections.controller.ts
  server/src/collections/collections.service.ts
  server/yarn.lock
Labels: size/M

#157 update upload csv column length check
  client/src/components/insert/Container.tsx
  client/src/components/insert/Types.ts
Labels: size/S

#158 fix: Refine advanced search
  client/src/components/advancedSearch/Dialog.tsx
Labels: size/S

#155 add spent time when accessing milvus
  server/src/app.module.ts
  server/src/collections/collections.controller.ts
  server/src/interceptors/index.ts
  server/src/partitions/partitions.controller.ts
  server/src/schema/schema.controller.ts
Labels: size/M

#165 fix docker run
  server/package.json
Labels: size/XS

#174 upgrade nest from v7 to v8/ remove useless fiels
  server/package.json
  server/src/middlewares/logger.ts
  server/src/utils/ConsoleLogger.ts
  server/yarn.lock
Labels: size/XL

#173 Fix vector search style problem and update insert uploading validation check warning
  client/src/components/grid/Table.tsx
  client/src/components/insert/Container.tsx
  client/src/components/insert/Import.tsx
  client/src/components/insert/Preview.tsx
  client/src/components/insert/Types.ts
  client/src/components/uploader/Types.ts
  client/src/components/uploader/Uploader.tsx
  client/src/consts/Insert.ts
  client/src/consts/Milvus.tsx
  client/src/http/Field.ts
  client/src/i18n/cn/insert.ts
  client/src/i18n/cn/search.ts
  client/src/i18n/en/insert.ts
  client/src/i18n/en/search.ts
  client/src/pages/schema/Types.ts
  client/src/pages/seach/SearchParams.tsx
  client/src/pages/seach/Styles.ts
  client/src/pages/seach/VectorSearch.tsx
Labels: size/L

#176 fix client side test case error
  client/src/components/__test__/layout/Layout.spec.tsx
Labels: size/XS

#175 Add vector search on overview page
  client/src/components/menu/NavMenu.tsx
  client/src/i18n/cn/button.ts
  client/src/i18n/en/button.ts
  client/src/pages/overview/collectionCard/CollectionCard.tsx
  client/src/pages/seach/VectorSearch.tsx
Labels: size/M

#177 add search input and tab list test
  client/src/components/__test__/customInput/SearchInput.spec.tsx
  client/src/components/__test__/customTabList/CustomTabList.spec.tsx
  client/src/components/__test__/layout/Layout.spec.tsx
  client/src/components/customInput/SearchInput.tsx
Labels: size/L

#181 enable server side test case
  server/src/app.controller.spec.ts
  server/src/collections/collections.controller.spec.ts
  server/src/collections/collections.service.spec.ts
  server/src/milvus/milvus.controller.spec.ts
  server/src/milvus/milvus.controller.ts
  server/src/milvus/milvus.service.mock.ts
  server/src/partitions/partitions.controller.spec.ts
  server/src/partitions/partitions.service.spec.ts
  server/src/partitions/partitions.service.ts
  server/src/schema/schema.controller.spec.ts
  server/src/schema/schema.service.spec.ts
  server/src/schema/schema.service.ts
  server/src/users/users.service.spec.ts
Labels: size/M

#180 add created time in collection
  client/src/http/Collection.ts
  client/src/i18n/cn/collection.ts
  client/src/i18n/en/collection.ts
  client/src/pages/collections/Collections.tsx
  server/generate-csv.ts
  server/package.json
  server/src/collections/collections.service.ts
  server/yarn.lock
Labels: size/M

#183 add partition time and fix created time
  client/src/http/Collection.ts
  client/src/http/Partition.ts
  client/src/i18n/cn/partition.ts
  client/src/i18n/en/partition.ts
  client/src/pages/collections/Collections.tsx
  client/src/pages/partitions/Partitions.tsx
  server/src/partitions/partitions.service.ts
Labels: size/M

#186 update node sdk version
  server/package.json
  server/yarn.lock
Labels: size/S

#185 add expandable left nav
  client/src/components/menu/NavMenu.tsx
Labels: size/L

#187 add show index build progres
  client/src/components/customProgress/CustomLinearProgress.tsx
  client/src/components/customProgress/Types.ts
  client/src/http/Index.ts
  client/src/i18n/cn/index.ts
  client/src/i18n/en/index.ts
  client/src/pages/overview/collectionCard/CollectionCard.tsx
  client/src/pages/schema/IndexTypeElement.tsx
  server/src/schema/dto.ts
Labels: size/L
