Repository milvus-io/milvus-insight, pull requests merged in 2021-08, with the labels that each got.

#189 fix meun item transition fail
  client/src/components/menu/NavMenu.tsx
Labels: size/M

#188 Feat/check insight
  .github/workflows/client.ovpn
  .github/workflows/dev.yml
  checkInsight.js
  server/src/app.controller.ts
Labels: size/L

#191 fix k8s action
  .github/workflows/dev.yml
Labels: size/XS

#193 fix k8s action
  .github/workflows/dev.yml
Labels: size/XS

#192 Add dimension validation before search
  client/src/i18n/cn/search.ts
  client/src/i18n/en/search.ts
  client/src/pages/seach/Styles.ts
  client/src/pages/seach/Types.ts
  client/src/pages/seach/VectorSearch.tsx
  client/src/utils/search.ts
Labels: size/L

#196 set menu default collapsed
  client/src/components/menu/NavMenu.tsx
Labels: size/XS

#195 add helmet package
  server/package.json
  server/src/main.ts
  server/yarn.lock
Labels: size/S

#197 * update readme
  .github/images/screenshot.png
  server/generate-csv.ts
  server/package.json
  server/src/main.ts
  server/yarn.lock
Labels: size/S

#199 Hide cache for now
  server/src/collections/collections.controller.ts
Labels: size/M

#202 fix getting loaded collections
  client/src/http/Collection.ts
  client/src/pages/collections/Types.ts
  client/src/pages/overview/Overview.tsx
Labels: size/S

#203 add more comments, remove unused modules
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/auth/const.ts
  server/src/auth/jwt.strategy.ts
  server/src/auth/local.strategy.ts
  server/src/schema/schema.controller.ts
  server/src/users/users.module.ts
  server/src/users/users.service.spec.ts
  server/src/users/users.service.ts
Labels: size/L

#206 Fix create index show result before showing creating progress
  client/src/context/Root.tsx
  client/src/context/Types.ts
  client/src/pages/schema/IndexTypeElement.tsx
  client/src/pages/schema/Schema.tsx
  client/src/types/Milvus.ts
Labels: size/M

#208 Update node sdk
  server/package.json
  server/src/cache/config.ts
  server/src/collections/collections.service.ts
  server/src/collections/dto.ts
  server/src/milvus/milvus.service.ts
  server/src/partitions/partitions.service.ts
  server/src/schema/dto.ts
  server/src/schema/schema.controller.ts
  server/src/schema/schema.service.ts
  server/yarn.lock
Labels: size/L

#211 fix hemlet and update readme
  README.md
  server/src/main.ts
Labels: size/S

#213 Create index add code mode
  client/.prettierrc
  client/package.json
  client/public/index.html
  client/src/components/__test__/copy/Copy.spec.tsx
  client/src/components/advancedSearch/CopyButton.tsx
  client/src/components/advancedSearch/Types.ts
  client/src/components/advancedSearch/index.tsx
  client/src/components/code/CodeBlock.tsx
  client/src/components/code/CodeView.tsx
  client/src/components/code/Types.ts
  client/src/components/copy/Copy.tsx
  client/src/components/customButton/CustomIconButton.tsx
  client/src/components/customDialog/CustomDialog.tsx
  client/src/components/customDialog/CustomDialogTitle.tsx
  client/src/components/customDialog/DeleteDialogTemplate.tsx
  client/src/components/customDialog/DialogTemplate.tsx
  client/src/components/customDialog/Types.ts
  client/src/components/customProgress/CustomLinearProgress.tsx
  client/src/components/customSwitch/CustomSwitch.tsx
  client/src/components/customSwitch/Types.ts
  client/src/components/customTabList/CustomTabList.tsx
  client/src/components/customTabList/Types.ts
  client/src/components/grid/Grid.tsx
  client/src/components/grid/Table.tsx
  client/src/components/grid/TablePaginationActions.tsx
  client/src/components/grid/ToolBar.tsx
  client/src/components/insert/Import.tsx
  client/src/components/layout/GlobalToolbar.tsx
  client/src/components/layout/Header.tsx
  client/src/components/menu/NavMenu.tsx
  client/src/components/status/Status.tsx
  client/src/context/Auth.tsx
  client/src/i18n/cn/common.ts
  client/src/i18n/en/common.ts
  client/src/index.css
  client/src/pages/connect/Connect.tsx
  client/src/pages/overview/collectionCard/CollectionCard.tsx
  client/src/pages/overview/statisticsCard/StatisticsCard.tsx
  client/src/pages/schema/Create.tsx
  client/src/pages/schema/IndexTypeElement.tsx
  client/src/pages/schema/Schema.tsx
  client/src/styles/common.css
  client/src/styles/theme.ts
  client/src/utils/Format.ts
  client/src/utils/code/Js.ts
  client/src/utils/code/Py.ts
  client/src/utils/code/Types.ts
  client/yarn.lock
Labels: size/XXL

#214 Update create index js and py template
  client/src/utils/code/Js.ts
  client/src/utils/code/Py.ts
Labels: size/XS

#215 Fix not show id field in vector search
  client/src/pages/seach/VectorSearch.tsx
  client/src/utils/search.ts
Labels: size/S

#217 add community btn
  client/src/assets/icons/people.svg
  client/src/assets/icons/slack.svg
  client/src/assets/imgs/wechat_qrcode.png
  client/src/components/menu/CommunityBtn.tsx
  client/src/components/menu/NavMenu.tsx
  client/src/i18n/cn/common.ts
  client/src/i18n/en/common.ts
Labels: size/L

#216 Add default selected partition and field in option selectors
  client/src/components/insert/Container.tsx
  client/src/pages/seach/VectorSearch.tsx
Labels: size/S

#218 remove warning
  client/src/components/menu/CommunityBtn.tsx
Labels: size/XS

#219 Update sdk to latest
  client/src/http/Collection.ts
  client/src/http/Index.ts
  client/src/pages/collections/Collections.tsx
  client/src/pages/collections/Types.ts
  client/src/pages/schema/Create.tsx
  client/src/pages/schema/IndexTypeElement.tsx
  client/src/pages/schema/Types.ts
  client/src/pages/seach/Types.ts
  client/src/pages/seach/VectorSearch.tsx
  client/src/utils/code/Py.ts
  client/src/utils/code/Types.ts
  server/package.json
  server/src/collections/collections.service.ts
  server/src/collections/dto.ts
  server/src/partitions/partitions.service.ts
  server/src/schema/dto.ts
  server/yarn.lock
Labels: size/L

#222 Add loading status
  client/src/components/cards/EmptyCard.tsx
  client/src/components/cards/Types.ts
  client/src/components/status/Status.tsx
  client/src/components/status/StatusIcon.tsx
  client/src/components/status/Types.ts
  client/src/consts/Milvus.tsx
  client/src/hooks/Dialog.tsx
  client/src/http/Collection.ts
  client/src/http/Partition.ts
  client/src/i18n/cn/common.ts
  client/src/i18n/cn/overview.ts
  client/src/i18n/en/common.ts
  client/src/i18n/en/overview.ts
  client/src/pages/collections/Collections.tsx
  client/src/pages/collections/Types.ts
  client/src/pages/overview/Overview.tsx
  client/src/pages/overview/collectionCard/CollectionCard.tsx
  client/src/pages/overview/collectionCard/Types.ts
  client/src/pages/partitions/Types.ts
  server/generate-csv.ts
  server/src/collections/collections.service.ts
  server/src/collections/dto.ts
  server/src/utils/Const.ts
Labels: size/L
